name: PugNewEnchants
version: '1.0-SNAPSHOT'
main: me.mopslops.pugnewenchants.PugNewEnchants
api-version: '1.21'
commands:
  giveenchantmentbook:
    description: Gives a player an enchantment book.
    usage: /<command> <enchantment> <level>